### PR TITLE
Merge ams/next into master

### PR DESCRIPTION
**Pull request by ams**
See https://github.com/LM-3/chaos/issues/1; I might just as well merge this as is and then fix it when quickly get fed up with usim not talking Chaos (which will be very quick).

### CODE REVIEW

**Comment by ams** [comment]
@larsbrinkhoff @bictorv what say ye?  Adding you as some kind of reviewer since you do Chaos as well.

**Comment by larsbrinkhoff** [comment]
WALL OF COMMITS

**Comment by larsbrinkhoff** [comment]
Of course, it's nice to resolve merge conflicts and failing builds.

**Comment by ams** [comment]
Will do that later today. :-)

**Comment by bictorv** [comment]
I agree, this is way too much to review.

**Comment by ams** [comment]
My intent wasn’t so much the exact commits, but rather restoring the “Chaosnet for Unix” with support for Linux, Unix sockets, and what not.  The old code was only meant to really support usim, but this would be a better fit in the grand scheme of things I think.

**Comment by ams** [comment]
Dropping this PR -- Chaos will ensue.

**Pull request closed without merging**
